CREATE TABLE IF NOT EXISTS submissions (
  id                TEXT PRIMARY KEY,
  timestamp         TEXT NOT NULL,
  fullname          TEXT,
  phone             TEXT,
  email             TEXT,
  age               INTEGER,
  gender            TEXT,
  address           TEXT,
  cccd              TEXT,
  cccd_date         TEXT,
  cccd_place        TEXT,
  run_tay           TEXT,
  can_thi           TEXT,
  mo_hoi_tay        TEXT,
  education         TEXT,
  company           TEXT,
  experience        INTEGER,
  salary            TEXT,
  start_date        TEXT,
  pandora_contact   TEXT,
  pandora_interview TEXT,
  pandora_contractor TEXT,
  bank_name         TEXT,
  bank_account      TEXT,
  cccd_photo        TEXT,
  cccd_photo_back   TEXT,
  bank_photo        TEXT
);
